site_name: fluidize-python
repo_url: https://github.com/Fluidize-Inc/fluidize-python
site_url: https://Fluidize-Inc.github.io/fluidize-python
site_description: Python package for automatic generation of scientific computing software pipelines.
site_author: Henry Bae
edit_uri: edit/main/docs/
repo_name: Fluidize-Inc/fluidize-python
copyright: Maintained by <a href="https://Fluidize-Inc.com">Fluidize-Inc</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["fluidize"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fluidize-Inc/fluidize-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fluidize-python

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
